// Generated by scripts/harvest.ts — do not hand-edit. Regenerate with:
//   pnpm tsx scripts/harvest.ts
// Every criterion below passed validate(): its source_text is a verbatim quote
// from the fetched page. See scripts/harvest-report.md for what was rejected.

export interface SeedCriterion {
  field: string;
  operator: string;
  value: number | string | Array<number | string>;
  display_text: string;
  source_text: string;
}

export type OpportunityCategory =
  | "scholarship" | "fellowship" | "grant" | "hackathon"
  | "internship" | "programme" | "event" | "competition";

export interface SeedOpportunity {
  name: string;
  provider: string | null;
  url: string;
  deadline: string | null;
  amount: string | null;
  category: OpportunityCategory;
  location_type: "india" | "abroad" | "online";
  funded: boolean;
  official_documents: string[];
  criteria: SeedCriterion[];
}

export const seedOpportunities: SeedOpportunity[] = [
  {
    name: "3D Websites Hackathon",
    provider: "Tanishq Kumar",
    url: "https://3d-websites-hackathon.devpost.com/",
    deadline: "2026-08-31",
    amount: "$55",
    category: "hackathon",
    location_type: "online",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "Students only",
        source_text: "Students only",
      },
      {
        field: "institution_type",
        operator: "not_in",
        value: ["Company","Professional organization"],
        display_text: "Companies/professional organizations excluded from participation",
        source_text: "Companies/professional organizations excluded from participation",
      }
    ],
  },
  {
    name: "Aditya Birla Capital Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Aditya Birla Capital Foundation",
    url: "https://www.indiascholarships.in/scholarships/aditya-birla-capital-scholarship",
    deadline: "2026-11-29",
    amount: "₹60k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Marksheet of previous class","Government-issued identity proof (Aadhaar/Voter ID)","Family Income Certificate","Current year admission proof (fee receipt/ID card)","Bank Passbook copy"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "Minimum Marks 60 %",
        source_text: "Minimum Marks 60 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Income Limit Up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      }
    ],
  },
  {
    name: "Aditya Birla Scholarship Programme 2026-27: Application Form, Eligibility & Selection List",
    provider: "Aditya Birla Group",
    url: "https://www.indiascholarships.in/scholarships/aditya-birla-scholarship-programme",
    deadline: "2026-10-30",
    amount: "₹3.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aditya Birla Scholarship application form","Letters of recommendation from faculty/director","Entrance exam scorecard (CAT/JEE/CLAT/etc.)","Recent passport size photograph","Short essays as specified by the foundation"],
    criteria: [
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "Category / Caste General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "Agentic Cinema: The Blockbuster Hackathon",
    provider: "Devpost",
    url: "https://agentic-cinema.devpost.com",
    deadline: "2026-09-09",
    amount: "$ 75,000 in prizes",
    category: "hackathon",
    location_type: "online",
    funded: true,
    official_documents: ["Official Rules"],
    criteria: [
      {
        field: "nationality",
        operator: "not_in",
        value: ["Afghanistan","Antarctica","Belarus","Brazil","China","Crimea","Cuba","Djibouti","Donetsk People’s Republic","Iran Islamic Republic of","Iraq","Italy","Kazakhstan","Korea Democratic People's Republic of","Luhansk People’s Republic","Quebec","Russia","Somalia","Sudan","Syrian Arab Republic","Venezuela","Vietnam","Western Sahara"],
        display_text: "Specific countries/territories excluded",
        source_text: "Specific countries/territories excluded",
      }
    ],
  },
  {
    name: "AICTE Pragati Scholarship for Girl Students 2026-27",
    provider: "All India Council for Technical Education (AICTE), Government of India",
    url: "https://www.indiascholarships.in/scholarships/aicte-pragati-scholarship-for-girl-students",
    deadline: "2026-10-30",
    amount: "₹50k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar card of the girl student","Family Income Certificate (< ₹8 Lakhs)","Class 10 & 12 marksheets","Admission receipt and AICTE approved college bonafide certificate","Aadhaar-seeded bank account details"],
    criteria: [
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Female students",
        source_text: "Note: Restricted to AICTE-approved institutions and female students.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Annual family income must be at most ₹8 Lakhs per year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 33,
        display_text: "Minimum marks percentage: at least 33%",
        source_text: "Minimum Marks 33 %",
      },
      {
        field: "institution_type",
        operator: "eq",
        value: "AICTE-approved",
        display_text: "Institution type must be AICTE-approved",
        source_text: "Note: Restricted to AICTE-approved institutions and female students.",
      }
    ],
  },
  {
    name: "All Things Agentic Hackathon",
    provider: "Devpost",
    url: "https://allthingsagentichackathon.devpost.com",
    deadline: "2026-08-31",
    amount: "$180,000 in prizes",
    category: "hackathon",
    location_type: "online",
    funded: true,
    official_documents: ["View full rules","FAQs","Official Rules"],
    criteria: [
      {
        field: "institution_type",
        operator: "eq",
        value: "Incorporated",
        display_text: "Must be submitting on behalf of an incorporated organization",
        source_text: "Must be submitting on behalf of an organization that is incorporated, and you must provide a corporate email address",
      }
    ],
  },
  {
    name: "Amazon Future Engineer Scholarship (India) 2026-27: Application Form, Eligibility & Selection List",
    provider: "Amazon India & Foundation for Excellence (FFE)",
    url: "https://www.indiascholarships.in/scholarships/amazon-future-engineer-scholarship-india",
    deadline: "2026-12-30",
    amount: "₹50k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar Card","Class 10/12 Marksheet","Income Certificate (Family income < ₹3 Lakhs)","Admission Proof (B.E./B.Tech/Integrated M.Tech fee receipt)","Entrance Exam Scorecard","Bank Passbook"],
    criteria: [
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "Year of study equals 1",
        source_text: "Education Level 1st Year Undergraduate (UG)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "Minimum percentage >= 60",
        source_text: "Minimum Marks 60 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 300000,
        display_text: "Annual family income <= 300000",
        source_text: "Income Limit Up to ₹3.0 Lakh/year",
      },
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Gender equals female",
        source_text: "Is this scholarship open to male students? No, the Amazon Future Engineer Scholarship in India is strictly for female students pursuing computer science or engineering courses.",
      }
    ],
  },
  {
    name: "Azim Premji Scholarship 2026",
    provider: "Azim Premji Foundation",
    url: "https://www.buddy4study.com/scholarship/azim-premji-scholarship-2026",
    deadline: "2026-08-31",
    amount: "₹30,000 per month",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Recent passport-sized photograph of applicant","Applicant’s signature on a paper","Aadhaar card","Bank details (passbook/statement)","Class 10 and 12 marksheet","University admission proof (bonafide/fee receipt)"],
    criteria: [
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "Must be admitted to first year in 2025-26",
        source_text: "have taken admission in the first year for the academic year 2025-26",
      },
      {
        field: "institution_type",
        operator: "in",
        value: ["Government","Private"],
        display_text: "Must be admitted to a government or private university",
        source_text: "be admitted to a recognised undergraduate degree or diploma course at a government/private university in India",
      }
    ],
  },
  {
    name: "BCWD Post-Matric Scholarship, Karnataka 2027",
    provider: "Backward Classes Welfare Department, Government of Karnataka",
    url: "https://www.buddy4study.com/scholarship/bcwd-post-matric-scholarship-karnataka-2027",
    deadline: "2026-08-31",
    amount: "Up to ₹20,000 annually",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar details","Caste Certificate","Income certificate","Residency proof","Disability certificate (if applicable)","Admission proof/ID proof","Postmatric Manual Advertisement"],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "be a permanent resident of Karnataka",
        source_text: "be a permanent resident of Karnataka",
      },
      {
        field: "category",
        operator: "eq",
        value: "OBC",
        display_text: "be included in the OBC list notified by the central/state",
        source_text: "be included in the OBC list notified by the central/state",
      },
      {
        field: "institution_type",
        operator: "in",
        value: ["Government","Aided","Private"],
        display_text: "be pursuing postmatric courses in government/local body/aided institutions/recognised unaided private institutions under the statutory universities of Karnataka",
        source_text: "be pursuing postmatric courses in government/local body/aided institutions/recognised unaided private institutions under the statutory universities of Karnataka",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 250000,
        display_text: "have an annual family income not exceeding ₹2,50,000 (Category 1) or ₹1,00,000 (Category 2A, 3A, 3B)",
        source_text: "have an annual family income not exceeding ₹2,50,000 (Category 1) or ₹1,00,000 (Category 2A, 3A, 3B)",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 100000,
        display_text: "have an annual family income not exceeding ₹2,50,000 (Category 1) or ₹1,00,000 (Category 2A, 3A, 3B)",
        source_text: "have an annual family income not exceeding ₹2,50,000 (Category 1) or ₹1,00,000 (Category 2A, 3A, 3B)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "have passed the previous year's annual examination with a minimum mark of 60% (Category 1) or 70% (others)",
        source_text: "have passed the previous year's annual examination with a minimum mark of 60% (Category 1) or 70% (others)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 70,
        display_text: "have passed the previous year's annual examination with a minimum mark of 60% (Category 1) or 70% (others)",
        source_text: "have passed the previous year's annual examination with a minimum mark of 60% (Category 1) or 70% (others)",
      }
    ],
  },
  {
    name: "Bharti Airtel Scholarship Program 2026-27: Application Form, Eligibility & Selection List",
    provider: "Bharti Foundation",
    url: "https://www.indiascholarships.in/scholarships/bharti-airtel-scholarship-program",
    deadline: "2026-10-30",
    amount: "₹3.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar/PAN/Driving License","Admission Proof","Class 12 Marksheet","JEE/University Entrance Scorecard","Family Income Proof","Bank Account Details (Aadhaar-linked)","Institution Bank Details","Passport Photo","Statement of Purpose","Hostel/PG Rent Receipts (if applicable)","Proof of Extra-curricular activities/achievements (if applicable)"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Income Limit Up to ₹8.0 Lakh/year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "First-year undergraduate engineering students admitted to top 50 NIRF-ranked engineering institutes (2026-27)",
        source_text: "Candidates must be first-year undergraduate engineering students admitted to a top 50 NIRF-ranked engineering institute for the 2026-27 academic year",
      },
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Female (girl students) preference",
        source_text: "Preference is given to girl students, single-parent households, and disabled candidates",
      },
      {
        field: "branch",
        operator: "in",
        value: ["Engineering","Computer Science","Electronics","Mechanical","Civil","Chemical","CSE"],
        display_text: "Engineering",
        source_text: "Candidates must be first-year undergraduate engineering students admitted to a top 50 NIRF-ranked engineering institute for the 2026-27 academic year",
      }
    ],
  },
  {
    name: "BITS Pilani Board Topper & Alumni Endowed Scholarships 2026-27: Application Form, Eligibility & Selection List",
    provider: "BITS Alumni Association & BITS Pilani Administration",
    url: "https://www.indiascholarships.in/scholarships/bits-pilani-board-topper-alumni-scholarships",
    deadline: "2026-10-30",
    amount: "₹6.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Board Rank Certificate","Class 12 Marksheet","Parental Income Certificate","CGPA Transcript"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 80,
        display_text: "Minimum Marks 80%",
        source_text: "Minimum Marks 80 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Income Limit Up to ₹8.0 Lakh/year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "category",
        operator: "in",
        value: ["General","OBC","SC","ST"],
        display_text: "Category / Caste General, OBC, SC, ST",
        source_text: "Category / Caste General, OBC, SC, ST",
      }
    ],
  },
  {
    name: "Buddy4Study Education Funding Program For Medical and Allied Health Sciences",
    provider: "Buddy4Study Education Funding Program For Medical and Allied Health Sciences",
    url: "https://forms.gle/nziMHYWkqdKQGWyv7",
    deadline: "2026-08-31",
    amount: "Funding Solution via a mix of funding opportunities",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: [],
    criteria: [
      {
        field: "region",
        operator: "eq",
        value: "India",
        display_text: "region equals India",
        source_text: "This initiative is open to students who are currently pursuing or seeking admission to any recognised Medical or Allied Health Sciences programme at an institution in India.",
      }
    ],
  },
  {
    name: "Buddy4Study India Foundation Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Buddy4Study India Foundation",
    url: "https://www.indiascholarships.in/scholarships/buddy4study-india-foundation-scholarship",
    deadline: "2026-08-30",
    amount: "₹75k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Previous Class Marksheet","Aadhaar Card","Current Year Admission Proof (ID Card / Fee Receipt)","Passport-size Photo","Income Proof / Salary Slip"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Income limit up to ₹8.0 Lakh/year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      }
    ],
  },
  {
    name: "CM Raitha Vidya Nidhi - Farmer's Children Scholarship (Karnataka) 2026-27",
    provider: "Agriculture Department, Government of Karnataka",
    url: "https://www.indiascholarships.in/scholarships/cm-raitha-vidya-nidhi-farmers-children-scholarship-karnataka",
    deadline: "2026-12-30",
    amount: "₹11k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["FRUITS ID (Farmer ID)","Aadhaar Card","Student ID Proof","Previous Year Marksheet","Bank Passbook"],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "Domicile State Karnataka",
        source_text: "Domicile State Karnataka",
      }
    ],
  },
  {
    name: "Coursera Plus",
    provider: "Coursera Plus",
    url: "https://imp.i384100.net/c/7449621/4017009/14726",
    deadline: "2026-08-31",
    amount: "Access to 10,000+ courses spanning AI, business, and technology",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: [],
    criteria: [
      {
        field: "region",
        operator: "eq",
        value: "India",
        display_text: "residency in India",
        source_text: "Offer available for residents of India only.",
      }
    ],
  },
  {
    name: "DBT Biotech Industrial Training Programme (BITP) 2026-27",
    provider: "Department of Biotechnology, Ministry of Science and Technology, Government of India",
    url: "https://www.buddy4study.com/scholarship/dbt-biotech-industrial-training-programme-bitp-2026",
    deadline: "2026-09-06",
    amount: "Up to ₹10,000 per month",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Passport-size photograph in JPEG format","Signature in JPEG format","Self-attested copy of the final certificate/mark-sheet of graduation and post-graduation, indicating the cumulative percentage of marks or CGPA","Debit Card/Credit card/UPI or internet banking details"],
    criteria: [
      {
        field: "branch",
        operator: "in",
        value: ["Biotechnology","Bioinformatics"],
        display_text: "Branch in Biotechnology or Bioinformatics",
        source_text: "To be eligible, an applicant must:- hold a B.E./B.Tech/M.Sc./M.Tech./M.VSc./MBA degree in Biotechnology/ Bioinformatics OR be admitted to a DBT postgraduate teaching program in Biotechnology",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 50,
        display_text: "Minimum 50% marks or equivalent",
        source_text: "have acquired a minimum of 50% marks or equivalent grades in the year 2023, 2024, or 2025",
      }
    ],
  },
  {
    name: "Digital Gujarat Scholarship Portal (Pre-Matric & Post-Matric) 2026-27",
    provider: "Government of Gujarat",
    url: "https://www.indiascholarships.in/scholarships/digital-gujarat-scholarship-portal",
    deadline: "2026-09-29",
    amount: "₹60k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar Card","Caste Certificate","Income Certificate (issued by Mamlatdar/TDO)","School/College Leaving Certificate","Hostel Certificate (if applicable)","Bank passbook page"],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Gujarat",
        display_text: "Domicile State Gujarat",
        source_text: "Domicile State Gujarat",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Income Limit Up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      }
    ],
  },
  {
    name: "DRDO SSPL Junior Research Fellowship 2026",
    provider: "Solid State Physics Laboratory (SSPL), DRDO",
    url: "https://www.buddy4study.com/scholarship/drdo-sspl-junior-research-fellow-2026",
    deadline: "2026-09-09",
    amount: "₹37,000 per month",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Application form","2 passport-size photographs","Academic marksheet","Caste Certificate","Experience certificates( If applicable)","Copies of research publications","No Objection Certificate (For Government/PSU/Autonomous Bodies Employees)"],
    criteria: [
      {
        field: "nationality",
        operator: "eq",
        value: "Indian",
        display_text: "Indian nationality",
        source_text: "be an Indian national",
      },
      {
        field: "age",
        operator: "lte",
        value: 28,
        display_text: "Age is 28 years or below",
        source_text: "be 28 years of age or below",
      }
    ],
  },
  {
    name: "DRDO SSPL Research Associate 2026",
    provider: "Solid State Physics Laboratory (SSPL), DRDO",
    url: "https://www.buddy4study.com/scholarship/drdo-sspl-research-associate-2026",
    deadline: "2026-09-09",
    amount: "₹67,000 per month",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Duly filled application form","2 passport-size photographs","Academic marksheet","Caste Certificate","Experience certificates( If applicable)","Copies of research publications","No Objection Certificate (For Government/PSU/Autonomous Bodies Employees)"],
    criteria: [
      {
        field: "nationality",
        operator: "eq",
        value: "Indian",
        display_text: "Nationality equals Indian",
        source_text: "be an Indian national.",
      },
      {
        field: "age",
        operator: "lte",
        value: 35,
        display_text: "Age <= 35",
        source_text: "be 35 years of age or below.",
      },
      {
        field: "branch",
        operator: "in",
        value: ["Physics","Electronics"],
        display_text: "PhD in Physics or Electronics",
        source_text: "hold either: A Ph.D. (or equivalent) in Physics/Electronics, or An M.E./M.Tech with 3 years of research experience in semiconductor materials, device fabrication, and characterization, along with at least one SCI-indexed research publication.",
      },
      {
        field: "experience_years",
        operator: "gte",
        value: 3,
        display_text: "Experience >= 3 years",
        source_text: "hold either: A Ph.D. (or equivalent) in Physics/Electronics, or An M.E./M.Tech with 3 years of research experience in semiconductor materials, device fabrication, and characterization, along with at least one SCI-indexed research publication.",
      }
    ],
  },
  {
    name: "DreamHacks 2026",
    provider: "DreamHacks",
    url: "https://dreamhacks-gt.devpost.com/",
    deadline: "2026-08-30",
    amount: "$25",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "age",
        operator: "gte",
        value: 13,
        display_text: "Ages 13 to 18 only",
        source_text: "Ages 13 to 18 only",
      },
      {
        field: "age",
        operator: "lte",
        value: 18,
        display_text: "Ages 13 to 18 only",
        source_text: "Ages 13 to 18 only",
      },
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "High school students only",
        source_text: "High school students only",
      },
      {
        field: "team_size",
        operator: "gte",
        value: 2,
        display_text: "Team required: 2 to 5 members",
        source_text: "Team required: 2 to 5 members",
      },
      {
        field: "team_size",
        operator: "lte",
        value: 5,
        display_text: "Team required: 2 to 5 members",
        source_text: "Team required: 2 to 5 members",
      },
      {
        field: "team_size",
        operator: "lte",
        value: 4,
        display_text: "You can work independently or in a team of up to four students.",
        source_text: "You can work independently or in a team of up to four students.",
      }
    ],
  },
  {
    name: "Foundation for Excellence (FFE) Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Foundation for Excellence",
    url: "https://www.indiascholarships.in/scholarships/foundation-for-excellence-ffe-scholarship",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: [],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 70,
        display_text: "Percentage must be at least 70%",
        source_text: "Minimum Marks 70 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 300000,
        display_text: "Annual family income must be up to ₹3.0 Lakh/year",
        source_text: "Income Limit Up to ₹3.0 Lakh/year",
      },
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "Category: General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "GyanDhan Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "GyanDhan",
    url: "https://www.indiascholarships.in/scholarships/gyandhan-scholarship",
    deadline: null,
    amount: "₹2.5 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar Card","Proof of enrollment/admission for 2026 intake","Resume/CV"],
    criteria: [
      {
        field: "branch",
        operator: "in",
        value: ["Engineering","Computer Science","Electronics","Mechanical","Civil","Chemical","CSE"],
        display_text: "Engineering (< ₹8L Income)",
        source_text: "Eligibility Summary Class 11-12, Graduation, Engineering (< ₹8L Income)",
      },
      {
        field: "annual_family_income",
        operator: "between",
        value: [0,800000],
        display_text: "Income < ₹8L (Engineering)",
        source_text: "Eligibility Summary Class 11-12, Graduation, Engineering (< ₹8L Income)",
      }
    ],
  },
  {
    name: "Hack the Habitat",
    provider: "Hack the Habitat",
    url: "https://hack-the-habitat-2026.devpost.com/",
    deadline: "2026-08-31",
    amount: "$1,000",
    category: "hackathon",
    location_type: "online",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "Students only",
        source_text: "Students only",
      },
      {
        field: "team_size",
        operator: "lte",
        value: 4,
        display_text: "Form a team of up to four participants or work individually.",
        source_text: "Form a team of up to four participants or work individually.",
      }
    ],
  },
  {
    name: "Hack The Limit",
    provider: "HackTheLimit",
    url: "https://hack-the-limit-1.devpost.com/",
    deadline: "2026-08-30",
    amount: "$350",
    category: "hackathon",
    location_type: "online",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "Students only",
        source_text: "Students only",
      }
    ],
  },
  {
    name: "Hacksocial 2026",
    provider: "Hacksocial",
    url: "https://hacksocial2026.devpost.com/",
    deadline: "2026-08-31",
    amount: "$3,979",
    category: "hackathon",
    location_type: "online",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "age",
        operator: "gte",
        value: 13,
        display_text: "Ages 13+ only",
        source_text: "Ages 13+ only",
      },
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "Students only",
        source_text: "Students only",
      }
    ],
  },
  {
    name: "Infosys Foundation STEM Stars Scholarship Program 2026-27: Application Form, Eligibility & Selection List",
    provider: "Infosys Foundation",
    url: "https://www.indiascholarships.in/scholarships/infosys-foundation-stem-stars-scholarship-program",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Recent passport-sized photograph","Class 12 marksheet and passing certificate","JEE Main/CET/NEET scorecard","Government-issued ID (Aadhaar/Voter ID/Passport/Ration Card)","Proof of current year admission (fee receipt/admission letter/institution ID/bonafide certificate)","Family income certificate (government-issued)","BPL card or Ayushman Bharat card (if applicable)","Electricity bills for past 6 months","Bank passbook/cancelled cheque","Receipts of academic expenses (course fees","hostel","mess","stationery","books"],
    criteria: [
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Female candidates only.",
        source_text: "Note: Female candidates only.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Income Limit Up to ₹8.0 Lakh/year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "region",
        operator: "eq",
        value: "India",
        display_text: "Geography: India",
        source_text: "Is the scholarship only for female students? Yes, the Infosys Foundation STEM Stars Scholarship is strictly for female candidates pursuing undergraduate STEM degrees (e.g., Engineering, MBBS, Integrated MSc, B.Arch) in India.",
      }
    ],
  },
  {
    name: "JSPN Scholarship 2026-27",
    provider: "Jaya Satya Pramoda Nidhi (JSPN)",
    url: "https://www.buddy4study.com/scholarship/jspn-scholarship-2026",
    deadline: "2026-08-30",
    amount: null,
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Identity proof","Aadhaar card number","Marksheet and certificates","Income certificate","Caste certificate (if applicable)","Disability certificate (if applicable)"],
    criteria: [
      {
        field: "nationality",
        operator: "eq",
        value: "Indian",
        display_text: "Indian",
        source_text: "Eligibility Indian citizens belonging to the Madhwa community",
      }
    ],
  },
  {
    name: "KJSSE CSI Gemini Hackday",
    provider: "MLH",
    url: "https://kjsse-csi-gemini-hackday.devpost.com/",
    deadline: "2026-08-30",
    amount: "₹ 10,000",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "Students only",
        source_text: "Students only",
      },
      {
        field: "team_size",
        operator: "between",
        value: [2,3],
        display_text: "Team required: 2 to 3 members",
        source_text: "Team required: 2 to 3 members",
      }
    ],
  },
  {
    name: "Kotak Kanya Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Kotak Education Foundation",
    url: "https://www.indiascholarships.in/scholarships/kotak-kanya-scholarship",
    deadline: "2026-08-30",
    amount: "₹1.5 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Class 10 & 12 marks memo showing >= 75%","Family Income Certificate (< ₹6 Lakhs)","College Fee receipts & admission letter","Student's Aadhaar card & passport photo","Aadhaar-seeded bank account details"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 75,
        display_text: "Minimum Marks 75 %",
        source_text: "Minimum Marks 75 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      },
      {
        field: "branch",
        operator: "in",
        value: ["Engineering","Medical","Management","Law","Technical","Architecture","Design","Computer Science","Electronics","Mechanical","Civil","Chemical","CSE"],
        display_text: "Course / Stream Engineering, Medical, Management, Law, Technical, Architecture, Design",
        source_text: "Course / Stream Engineering, Medical, Management, Law, Technical, Architecture, Design",
      },
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "First-year professional graduation",
        source_text: "Based on academic merit (minimum 75% in Class 12), family annual income under ₹6 Lakhs, and pursuing first-year professional graduation at recognized institutes.",
      },
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Female",
        source_text: "Note: Exclusively for girl students pursuing professional graduation.",
      }
    ],
  },
  {
    name: "L'Or'éal India For Young Women in Science (FYWIS) Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "L'Or'éal India",
    url: "https://www.indiascholarships.in/scholarships/loreal-fyws-scholarship",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Identity proof","Income certificate","Academic transcripts","Admission proof"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 85,
        display_text: "minimum 85% in Class 12 Science PCM/B for UG",
        source_text: "— Shortlisting based on academic merit (minimum 85% in Class 12 Science PCM/B for UG, minimum 60% in graduation for PG) and family income limit (<= ₹6,00,000 per annum)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "minimum 60% in graduation for PG",
        source_text: "— Shortlisting based on academic merit (minimum 85% in Class 12 Science PCM/B for UG, minimum 60% in graduation for PG) and family income limit (<= ₹6,00,000 per annum)",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "family income limit (<= ₹6,00,000 per annum)",
        source_text: "— Shortlisting based on academic merit (minimum 85% in Class 12 Science PCM/B for UG, minimum 60% in graduation for PG) and family income limit (<= ₹6,00,000 per annum)",
      },
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Open to women only",
        source_text: "L'Or'éal India For Young Women in Science (FYWIS) Scholarship 2026-27: Application Form, Eligibility & Selection List",
      }
    ],
  },
  {
    name: "Labour Department Scheme for Unorganized Workers' Children (Karnataka) 2026-27",
    provider: "Karnataka Labour Welfare Board, Government of Karnataka",
    url: "https://www.indiascholarships.in/scholarships/labour-department-scheme-for-unorganized-workers-children-karnataka",
    deadline: "2026-12-30",
    amount: "₹11k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Labour Card / Contribution Proof","Aadhaar Card","Student Marksheet","College Fee Receipt","Bank Passbook"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 420000,
        display_text: "Income Limit Up to ₹4.2 Lakh/year",
        source_text: "Income Limit Up to ₹4.2 Lakh/year",
      },
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "Domicile State Karnataka",
        source_text: "Domicile State Karnataka",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 50,
        display_text: "General category students require at least 50% marks in their previous exam.",
        source_text: "General category students require at least 50% marks in their previous exam.",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 45,
        display_text: "SC/ST students require at least 45% marks.",
        source_text: "SC/ST students require at least 45% marks.",
      }
    ],
  },
  {
    name: "LIC HFL Vidyadhan Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "LIC Housing Finance Limited",
    url: "https://www.indiascholarships.in/scholarships/lic-hfl-vidyadhan-scholarship",
    deadline: "2026-12-30",
    amount: "₹25k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Marksheet of previous qualifying exam","Aadhaar Card (Proof of Identity)","Income Certificate (annual family income < ₹3.6 Lakhs)","Current Year Admission Proof (Bonafide certificate, fee receipt, or college ID)","Bank account passbook copy or cancelled cheque"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 360000,
        display_text: "Income Limit Up to ₹3.6 Lakh/year",
        source_text: "Income Limit Up to ₹3.6 Lakh/year",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "Minimum Marks 60 %",
        source_text: "Minimum Marks 60 %",
      }
    ],
  },
  {
    name: "Midnight Hackathon: August 2026",
    provider: "Major League Hacking",
    url: "https://midnight-hackathon-august-2026.devpost.com/",
    deadline: "2026-08-30",
    amount: "$0",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "team_size",
        operator: "lte",
        value: 5,
        display_text: "Maximum team size: 5",
        source_text: "Each team can have a maximum of 5 members.",
      }
    ],
  },
  {
    name: "Narotam Sekhsaria Postgraduate Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Narotam Sekhsaria Foundation",
    url: "https://www.indiascholarships.in/scholarships/narotam-sekhsaria-postgraduate-scholarship",
    deadline: "2026-10-30",
    amount: "₹20.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Degree Certificate","Marksheets","GRE/GMAT/IELTS scores","Admission Letter","LORs","Passport"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 75,
        display_text: "Minimum Marks 75 %",
        source_text: "Minimum Marks 75 %",
      }
    ],
  },
  {
    name: "NSP Financial Assistance for Education to the Wards of Beedi/Cine/Iomc/Lsdm, Post-Matric 2026-27",
    provider: "Ministry of Labour and Employment, Government of India",
    url: "https://www.buddy4study.com/scholarship/nsp-financial-assistance-for-education-to-the-wards-of-beedi-cine-iomc-lsdm-post-matric-2026",
    deadline: "2026-10-31",
    amount: "Up to ₹25,000 per annum",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Scholarship Guidelines","Terms and Conditions","Source: https://scholarships.gov.in/"],
    criteria: [
      {
        field: "nationality",
        operator: "eq",
        value: "Indian",
        display_text: "be an Indian national",
        source_text: "be an Indian national",
      }
    ],
  },
  {
    name: "OP Jindal Engineer & Management Scholarships 2026",
    provider: "O. P. Jindal Group of Companies",
    url: "https://www.buddy4study.com/scholarship/op-jindal-engineer-management-scholarships-2026",
    deadline: "2026-09-15",
    amount: "Up to ₹1,50,000 per annum",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Brochure","Photo of the applicant","Educational certificates/marksheet","Business proposal in PDF format"],
    criteria: [
      {
        field: "branch",
        operator: "in",
        value: ["Civil Engineering","Electrical Engineering","Mechanical Engineering","Metallurgical Engineering"],
        display_text: "Eligible streams include Civil Engineering, Electrical Engineering, Mechanical Engineering, or Metallurgical Engineering (first three toppers from each year in these streams).",
        source_text: "To be eligible, an applicant must:- be the first three toppers from each year of the following engineering streams: Civil Engineering Electrical Engineering Mechanical Engineering Metallurgical Engineering OR be the first ten toppers from each year of management",
      }
    ],
  },
  {
    name: "OP Jindal Engineering & Management Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "OP Jindal Group",
    url: "https://www.indiascholarships.in/scholarships/op-jindal-engineering-management-scholarship",
    deadline: "2026-10-30",
    amount: "₹1.5 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Institutional nomination proof","academic transcripts/entrance ranks","business proposal","ID proof"],
    criteria: [
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "Category / Caste General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "Practice Submission",
    provider: "SYNCS",
    url: "https://practice-submission.devpost.com/",
    deadline: "2026-08-30",
    amount: "$238,123",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "student_status",
        operator: "eq",
        value: "Student",
        display_text: "Students only",
        source_text: "Students only",
      },
      {
        field: "team_size",
        operator: "between",
        value: [2,5],
        display_text: "Team required: 2 to 5 members",
        source_text: "Team required: 2 to 5 members",
      }
    ],
  },
  {
    name: "Raman Kant Munjal Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Raman Kant Munjal Foundation",
    url: "https://www.indiascholarships.in/scholarships/raman-kant-munjal-scholarship",
    deadline: "2026-08-30",
    amount: "₹5.5 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Class 10 Marksheet","Class 12 Marksheet","Proof of current academic enrollment (College ID/fee receipt)","Parent's PAN card & masked Aadhaar card","Annual parental income proof (ITR/Income Certificate/salary slips)","Applicant's bank account details (passbook/cancelled cheque)","Bank account statements of parents","Affidavit declaring document authenticity","LinkedIn Profile URL"],
    criteria: [
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "Year of study equals 1 (first-year UG)",
        source_text: "The Raman Kant Munjal Scholarship 2026 offers up to ₹5.5 Lakhs per year to first-year finance and commerce undergraduate students with family incomes under ₹6 Lakh.",
      },
      {
        field: "branch",
        operator: "eq",
        value: "Finance and Commerce",
        display_text: "Branch equals finance and commerce",
        source_text: "The Raman Kant Munjal Scholarship 2026 offers up to ₹5.5 Lakhs per year to first-year finance and commerce undergraduate students with family incomes under ₹6 Lakh.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Annual family income less than or equal to 600000",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 80,
        display_text: "Percentage at least 80%",
        source_text: "Minimum Marks 80 %",
      }
    ],
  },
  {
    name: "Reliance Foundation Scholarship 2026-27: UG Apply Online, Eligibility & Selection",
    provider: "Reliance Foundation",
    url: "https://www.indiascholarships.in/scholarships/reliance-foundation-undergraduate-scholarship",
    deadline: "2026-10-14",
    amount: "₹50k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Class 12 Marks memo showing >= 60%","Domicile / Indian Citizenship proof","Family Income Certificate (< ₹15 Lakhs)","College Admission confirmation & regular student bonafide","Aadhaar card & passport photo"],
    criteria: [
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "First year undergraduate",
        source_text: "Only students currently enrolled in the 1st year of a regular full-time undergraduate degree (academic year 2025-26) are eligible.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 1500000,
        display_text: "Household income ≤ ₹15 lakh per year",
        source_text: "You must have a household income of ₹15 lakh or less per annum.",
      }
    ],
  },
  {
    name: "SBI Asha Scholarship 2026-27: ₹15,000 | Eligibility, Last Date & Apply Online",
    provider: "SBI Foundation",
    url: "https://www.indiascholarships.in/scholarships/sbi-platinum-jubilee-asha-scholarship",
    deadline: "2026-10-30",
    amount: "₹20.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar Card","Passport Photo","Previous Year Marksheet","Income Certificate","Admission Proof","Bank Passbook"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 75,
        display_text: "Minimum Marks 75 %",
        source_text: "Minimum Marks 75 %",
      },
      {
        field: "cgpa",
        operator: "gte",
        value: 7,
        display_text: "Minimum CGPA 7.0",
        source_text: "Selection is based on academic merit (minimum 75% marks or 7.0 CGPA in the previous year), financial background (family income ≤₹3L for school, ≤₹6L for college), telephonic interview, and document verification.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Income limit up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      }
    ],
  },
  {
    name: "SemiCon Hackathon - Explore, Innovate & Build with Semiconductors | IIT Bombay - 2026",
    provider: "Indian Institute of Technology (IIT), Bombay",
    url: "https://unstop.com/hackathons/semicon-hackathon-explore-innovate-build-with-semiconductors-sarcathon-2026-iit-bombay-1744747",
    deadline: null,
    amount: "₹ 5,00,000",
    category: "hackathon",
    location_type: "india",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "team_size",
        operator: "between",
        value: [1,3],
        display_text: "Team Size 1 - 3 Members",
        source_text: "Team Size 1 - 3 Members",
      }
    ],
  },
  {
    name: "Siemens Scholarship Program 2026-27: Application Form, Eligibility & Selection List",
    provider: "Siemens India",
    url: "https://www.indiascholarships.in/scholarships/siemens-scholarship-program",
    deadline: "2026-10-30",
    amount: "₹1.2 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["SSC and HSC mark sheets","income proof","admission letter","age proof","bank details","photos (standard for such scholarships)"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 200000,
        display_text: "income <=2L",
        source_text: "Who can apply? First-year Govt. Engg. students in specified streams, age <=20, income <=2L, min marks.[1][4]",
      },
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "Simplify building your tech stack with AI",
    provider: "Stripe",
    url: "https://stripedhakahackathon.devpost.com/",
    deadline: "2026-08-30",
    amount: "$0",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "age",
        operator: "gte",
        value: 18,
        display_text: "Ages 18+ only",
        source_text: "Ages 18+ only",
      }
    ],
  },
  {
    name: "Smart City Hackathon Lahore",
    provider: "Code for Pakistan",
    url: "https://smart-city-hackathon-lahore.devpost.com/",
    deadline: "2026-08-30",
    amount: "$642",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [

    ],
  },
  {
    name: "SSP Pre-Matric & Post-Matric Scholarship (Karnataka) 2026-27",
    provider: "Government of Karnataka",
    url: "https://www.indiascholarships.in/scholarships/ssp-pre-matric-post-matric-scholarship-karnataka",
    deadline: "2026-11-29",
    amount: "₹1.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: [],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "Domicile State Karnataka",
        source_text: "Domicile State Karnataka",
      },
      {
        field: "category",
        operator: "in",
        value: ["SC","ST","OBC","Minority","EWS"],
        display_text: "SC, ST, OBC, Minority, General (EWS)",
        source_text: "Category / Caste SC, ST, OBC, Minority, General (EWS)",
      }
    ],
  },
  {
    name: "STEP eLearn – General Communication Online (10% Discount)",
    provider: "Buddy4Study",
    url: "https://www.buddy4study.com/scholarship/step-elearn-general-communication-online-category-one",
    deadline: "2026-12-31",
    amount: "₹1,349",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Parent's income certificate"],
    criteria: [
      {
        field: "nationality",
        operator: "eq",
        value: "Indian",
        display_text: "Open for Indian Adult learners and individuals who wish to improve their English language skills.",
        source_text: "Open for Indian Adult learners and individuals who wish to improve their English language skills.",
      }
    ],
  },
  {
    name: "STEP eLearn – General Communication Online (54% Discount)",
    provider: "Buddy4Study",
    url: "https://www.buddy4study.com/scholarship/step-elearn-general-communication-online-category-three",
    deadline: "2026-12-31",
    amount: "₹697",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Parent's income certificate"],
    criteria: [
      {
        field: "nationality",
        operator: "eq",
        value: "Indian",
        display_text: "Nationality equals Indian",
        source_text: "Open for Indian Adult learners and individuals who wish to improve their English language skills.",
      }
    ],
  },
  {
    name: "TATA AIA PARAS Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "TATA AIA Life Insurance",
    url: "https://www.indiascholarships.in/scholarships/tata-aia-paras-scholarship",
    deadline: "2026-11-29",
    amount: "₹15k+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Class 12 Marksheet","Income Certificate (less than 5 Lakhs)","Admission Proof (Fee receipt/College ID)","Aadhaar Card","Bank Passbook copy","Disability or Caste Certificate (if applicable)"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 50,
        display_text: "Minimum Marks 50 %",
        source_text: "Minimum Marks 50 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 500000,
        display_text: "Income Limit Up to ₹5.0 Lakh/year",
        source_text: "Income Limit Up to ₹5.0 Lakh/year",
      }
    ],
  },
  {
    name: "Tata Realty Scholarship for Girls 2026-27: Application Form, Eligibility & Selection List",
    provider: "Tata Realty and Infrastructure Limited",
    url: "https://www.indiascholarships.in/scholarships/tata-realty-scholarship-for-girls",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["Aadhaar Card","Class 10 and 12 Marksheets","Income Certificate (less than 5 Lakhs)","B.Arch Admission Proof","Current Year Fee Receipt","Bank Passbook copy"],
    criteria: [
      {
        field: "branch",
        operator: "eq",
        value: "B.Arch",
        display_text: "Branch: B.Arch",
        source_text: "Education Level UG (B.Arch)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "Minimum marks: 60%",
        source_text: "Minimum Marks 60 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 500000,
        display_text: "Annual family income limit: up to ₹5 Lakh per year",
        source_text: "Income Limit Up to ₹5.0 Lakh/year",
      },
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Gender: female",
        source_text: "Note: Exclusively for female students pursuing B.Arch degree.",
      }
    ],
  },
  {
    name: "The Great Agent Hackathon",
    provider: "Women In Product India",
    url: "https://the-great-agent-hackathon.devpost.com/",
    deadline: "2026-08-30",
    amount: "₹ 100,000",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "team_size",
        operator: "eq",
        value: 2,
        display_text: "Team size must be exactly 2 members",
        source_text: "Team required: 2 to 2 members",
      }
    ],
  },
  {
    name: "The WebMCP Challenge",
    provider: "Devpost",
    url: "https://webmcp.devpost.com",
    deadline: "2026-09-03",
    amount: "$ 35,000 in prizes",
    category: "hackathon",
    location_type: "online",
    funded: true,
    official_documents: [],
    criteria: [

    ],
  },
  {
    name: "Veteran Innovation Hackathon",
    provider: "Hacker Dojo",
    url: "https://veteran-innovation-hackathon.devpost.com/",
    deadline: "2026-08-30",
    amount: "$500",
    category: "hackathon",
    location_type: "abroad",
    funded: false,
    official_documents: [],
    criteria: [

    ],
  },
  {
    name: "VIT B.Tech GV School Development Programme (GVSDP) Merit Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Vellore Institute of Technology",
    url: "https://www.indiascholarships.in/scholarships/viteee-gvsdp-merit-scholarship",
    deadline: "2026-10-30",
    amount: "₹4.5 Lakh+",
    category: "scholarship",
    location_type: "india",
    funded: true,
    official_documents: ["VITEEE Scorecard & Admit card","Class 12 Marksheet","Parental Income Certificate (optional, for MCN check)"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 85,
        display_text: "Minimum marks 85 %",
        source_text: "Minimum Marks 85 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 2000000,
        display_text: "Income limit up to 20.0 Lakh/year",
        source_text: "Income Limit Up to ₹20.0 Lakh/year",
      }
    ],
  },
  {
    name: "VLSI Design Internship at Kukbit SL",
    provider: "Kukbit SL",
    url: "https://unstop.com/internships/vlsi-design-internship-kukbit-sl-1737771",
    deadline: null,
    amount: null,
    category: "internship",
    location_type: "india",
    funded: false,
    official_documents: [],
    criteria: [
      {
        field: "category",
        operator: "eq",
        value: "Undergraduate",
        display_text: "Eligibility: Undergraduate",
        source_text: "Undergraduate",
      },
      {
        field: "category",
        operator: "eq",
        value: "Postgraduate",
        display_text: "Eligibility: Postgraduate",
        source_text: "Postgraduate",
      },
      {
        field: "branch",
        operator: "in",
        value: ["Engineering","Computer Science","Electronics","Mechanical","Civil","Chemical","CSE"],
        display_text: "Eligibility: Engineering Students",
        source_text: "Engineering Students",
      }
    ],
  }
];
