// Generated by scripts/harvest.ts — do not hand-edit. Regenerate with:
//   pnpm tsx scripts/harvest.ts
// Every criterion below passed validate(): its source_text is a verbatim quote
// from the fetched page. See scripts/harvest-report.md for what was rejected.

export interface SeedCriterion {
  field: string;
  operator: string;
  value: number | string | Array<number | string>;
  display_text: string;
  source_text: string;
}

export interface SeedOpportunity {
  name: string;
  provider: string | null;
  url: string;
  deadline: string | null;
  amount: string | null;
  official_documents: string[];
  criteria: SeedCriterion[];
}

export const seedOpportunities: SeedOpportunity[] = [

];
