// Generated by scripts/harvest.ts — do not hand-edit. Regenerate with:
//   pnpm tsx scripts/harvest.ts
// Every criterion below passed validate(): its source_text is a verbatim quote
// from the fetched page. See scripts/harvest-report.md for what was rejected.

export interface SeedCriterion {
  field: string;
  operator: string;
  value: number | string | Array<number | string>;
  display_text: string;
  source_text: string;
}

export interface SeedOpportunity {
  name: string;
  provider: string | null;
  url: string;
  deadline: string | null;
  amount: string | null;
  official_documents: string[];
  criteria: SeedCriterion[];
}

export const seedOpportunities: SeedOpportunity[] = [
  {
    name: "Reliance Foundation Scholarship 2026-27: UG Apply Online, Eligibility & Selection",
    provider: "Reliance Foundation",
    url: "https://www.indiascholarships.in/scholarships/reliance-foundation-undergraduate-scholarship",
    deadline: "2026-10-14",
    amount: "₹50k+",
    official_documents: ["Class 12 Marks memo showing >= 60%","Domicile / Indian Citizenship proof","Family Income Certificate (< ₹15 Lakhs)","College Admission confirmation & regular student bonafide","Aadhaar card & passport photo"],
    criteria: [
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "First year undergraduate",
        source_text: "Only students currently enrolled in the 1st year of a regular full-time undergraduate degree (academic year 2025-26) are eligible.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 1500000,
        display_text: "Household income ≤ ₹15 lakh per year",
        source_text: "You must have a household income of ₹15 lakh or less per annum.",
      }
    ],
  },
  {
    name: "Foundation for Excellence (FFE) Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Foundation for Excellence",
    url: "https://www.indiascholarships.in/scholarships/foundation-for-excellence-ffe-scholarship",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    official_documents: [],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 70,
        display_text: "Percentage must be at least 70%",
        source_text: "Minimum Marks 70 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 300000,
        display_text: "Annual family income must be up to ₹3.0 Lakh/year",
        source_text: "Income Limit Up to ₹3.0 Lakh/year",
      },
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "Category: General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "Siemens Scholarship Program 2026-27: Application Form, Eligibility & Selection List",
    provider: "Siemens India",
    url: "https://www.indiascholarships.in/scholarships/siemens-scholarship-program",
    deadline: "2026-10-30",
    amount: "₹1.2 Lakh+",
    official_documents: ["SSC and HSC mark sheets","income proof","admission letter","age proof","bank details","photos (standard for such scholarships)"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 200000,
        display_text: "income <=2L",
        source_text: "Who can apply? First-year Govt. Engg. students in specified streams, age <=20, income <=2L, min marks.[1][4]",
      },
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "SBI Asha Scholarship 2026-27: ₹15,000 | Eligibility, Last Date & Apply Online",
    provider: "SBI Foundation",
    url: "https://www.indiascholarships.in/scholarships/sbi-platinum-jubilee-asha-scholarship",
    deadline: "2026-10-30",
    amount: "₹20.0 Lakh+",
    official_documents: ["Aadhaar Card","Passport Photo","Previous Year Marksheet","Income Certificate","Admission Proof","Bank Passbook"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 75,
        display_text: "Minimum Marks 75 %",
        source_text: "Minimum Marks 75 %",
      },
      {
        field: "cgpa",
        operator: "gte",
        value: 7,
        display_text: "Minimum CGPA 7.0",
        source_text: "Selection is based on academic merit (minimum 75% marks or 7.0 CGPA in the previous year), financial background (family income ≤₹3L for school, ≤₹6L for college), telephonic interview, and document verification.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Income limit up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      }
    ],
  },
  {
    name: "CM Raitha Vidya Nidhi - Farmer's Children Scholarship (Karnataka) 2026-27",
    provider: "Agriculture Department, Government of Karnataka",
    url: "https://www.indiascholarships.in/scholarships/cm-raitha-vidya-nidhi-farmers-children-scholarship-karnataka",
    deadline: "2026-12-30",
    amount: "₹11k+",
    official_documents: ["FRUITS ID (Farmer ID)","Aadhaar Card","Student ID Proof","Previous Year Marksheet","Bank Passbook"],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "Domicile State Karnataka",
        source_text: "Domicile State Karnataka",
      }
    ],
  },
  {
    name: "Labour Department Scheme for Unorganized Workers' Children (Karnataka) 2026-27",
    provider: "Karnataka Labour Welfare Board, Government of Karnataka",
    url: "https://www.indiascholarships.in/scholarships/labour-department-scheme-for-unorganized-workers-children-karnataka",
    deadline: "2026-12-30",
    amount: "₹11k+",
    official_documents: ["Labour Card / Contribution Proof","Aadhaar Card","Student Marksheet","College Fee Receipt","Bank Passbook"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 420000,
        display_text: "Income Limit Up to ₹4.2 Lakh/year",
        source_text: "Income Limit Up to ₹4.2 Lakh/year",
      },
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "Domicile State Karnataka",
        source_text: "Domicile State Karnataka",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 50,
        display_text: "General category students require at least 50% marks in their previous exam.",
        source_text: "General category students require at least 50% marks in their previous exam.",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 45,
        display_text: "SC/ST students require at least 45% marks.",
        source_text: "SC/ST students require at least 45% marks.",
      }
    ],
  },
  {
    name: "SSP Pre-Matric & Post-Matric Scholarship (Karnataka) 2026-27",
    provider: "Government of Karnataka",
    url: "https://www.indiascholarships.in/scholarships/ssp-pre-matric-post-matric-scholarship-karnataka",
    deadline: "2026-11-29",
    amount: "₹1.0 Lakh+",
    official_documents: [],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Karnataka",
        display_text: "Domicile State Karnataka",
        source_text: "Domicile State Karnataka",
      },
      {
        field: "category",
        operator: "in",
        value: ["SC","ST","OBC","Minority","General (EWS)"],
        display_text: "SC, ST, OBC, Minority, General (EWS)",
        source_text: "Category / Caste SC, ST, OBC, Minority, General (EWS)",
      }
    ],
  },
  {
    name: "GyanDhan Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "GyanDhan",
    url: "https://www.indiascholarships.in/scholarships/gyandhan-scholarship",
    deadline: null,
    amount: "₹2.5 Lakh+",
    official_documents: ["Aadhaar Card","Proof of enrollment/admission for 2026 intake","Resume/CV"],
    criteria: [
      {
        field: "branch",
        operator: "eq",
        value: "Engineering",
        display_text: "Engineering (< ₹8L Income)",
        source_text: "Eligibility Summary Class 11-12, Graduation, Engineering (< ₹8L Income)",
      },
      {
        field: "annual_family_income",
        operator: "between",
        value: [0,800000],
        display_text: "Income < ₹8L (Engineering)",
        source_text: "Eligibility Summary Class 11-12, Graduation, Engineering (< ₹8L Income)",
      }
    ],
  },
  {
    name: "Aditya Birla Scholarship Programme 2026-27: Application Form, Eligibility & Selection List",
    provider: "Aditya Birla Group",
    url: "https://www.indiascholarships.in/scholarships/aditya-birla-scholarship-programme",
    deadline: "2026-10-30",
    amount: "₹3.0 Lakh+",
    official_documents: ["Aditya Birla Scholarship application form","Letters of recommendation from faculty/director","Entrance exam scorecard (CAT/JEE/CLAT/etc.)","Recent passport size photograph","Short essays as specified by the foundation"],
    criteria: [
      {
        field: "category",
        operator: "eq",
        value: "General",
        display_text: "Category / Caste General",
        source_text: "Category / Caste General",
      }
    ],
  },
  {
    name: "Bharti Airtel Scholarship Program 2026-27: Application Form, Eligibility & Selection List",
    provider: "Bharti Foundation",
    url: "https://www.indiascholarships.in/scholarships/bharti-airtel-scholarship-program",
    deadline: "2026-10-30",
    amount: "₹3.0 Lakh+",
    official_documents: ["Aadhaar/PAN/Driving License","Admission Proof","Class 12 Marksheet","JEE/University Entrance Scorecard","Family Income Proof","Bank Account Details (Aadhaar-linked)","Institution Bank Details","Passport Photo","Statement of Purpose","Hostel/PG Rent Receipts (if applicable)","Proof of Extra-curricular activities/achievements (if applicable)"],
    criteria: [
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Income Limit Up to ₹8.0 Lakh/year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "First-year undergraduate engineering students admitted to top 50 NIRF-ranked engineering institutes (2026-27)",
        source_text: "Candidates must be first-year undergraduate engineering students admitted to a top 50 NIRF-ranked engineering institute for the 2026-27 academic year",
      },
      {
        field: "branch",
        operator: "eq",
        value: "engineering",
        display_text: "Engineering",
        source_text: "Candidates must be first-year undergraduate engineering students admitted to a top 50 NIRF-ranked engineering institute for the 2026-27 academic year",
      },
      {
        field: "gender",
        operator: "eq",
        value: "female",
        display_text: "Female (girl students) preference",
        source_text: "Preference is given to girl students, single-parent households, and disabled candidates",
      }
    ],
  },
  {
    name: "BITS Pilani Board Topper & Alumni Endowed Scholarships 2026-27: Application Form, Eligibility & Selection List",
    provider: "BITS Alumni Association & BITS Pilani Administration",
    url: "https://www.indiascholarships.in/scholarships/bits-pilani-board-topper-alumni-scholarships",
    deadline: "2026-10-30",
    amount: "₹6.0 Lakh+",
    official_documents: ["Board Rank Certificate","Class 12 Marksheet","Parental Income Certificate","CGPA Transcript"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 80,
        display_text: "Minimum Marks 80%",
        source_text: "Minimum Marks 80 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Income Limit Up to ₹8.0 Lakh/year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "category",
        operator: "in",
        value: ["General","OBC","SC","ST"],
        display_text: "Category / Caste General, OBC, SC, ST",
        source_text: "Category / Caste General, OBC, SC, ST",
      }
    ],
  },
  {
    name: "VIT B.Tech GV School Development Programme (GVSDP) Merit Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Vellore Institute of Technology",
    url: "https://www.indiascholarships.in/scholarships/viteee-gvsdp-merit-scholarship",
    deadline: "2026-10-30",
    amount: "₹4.5 Lakh+",
    official_documents: ["VITEEE Scorecard & Admit card","Class 12 Marksheet","Parental Income Certificate (optional, for MCN check)"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 85,
        display_text: "Minimum marks 85 %",
        source_text: "Minimum Marks 85 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 2000000,
        display_text: "Income limit up to 20.0 Lakh/year",
        source_text: "Income Limit Up to ₹20.0 Lakh/year",
      }
    ],
  },
  {
    name: "TATA AIA PARAS Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "TATA AIA Life Insurance",
    url: "https://www.indiascholarships.in/scholarships/tata-aia-paras-scholarship",
    deadline: "2026-11-29",
    amount: "₹15k+",
    official_documents: ["Class 12 Marksheet","Income Certificate (less than 5 Lakhs)","Admission Proof (Fee receipt/College ID)","Aadhaar Card","Bank Passbook copy","Disability or Caste Certificate (if applicable)"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 50,
        display_text: "Minimum Marks 50 %",
        source_text: "Minimum Marks 50 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 500000,
        display_text: "Income Limit Up to ₹5.0 Lakh/year",
        source_text: "Income Limit Up to ₹5.0 Lakh/year",
      }
    ],
  },
  {
    name: "Narotam Sekhsaria Postgraduate Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Narotam Sekhsaria Foundation",
    url: "https://www.indiascholarships.in/scholarships/narotam-sekhsaria-postgraduate-scholarship",
    deadline: "2026-10-30",
    amount: "₹20.0 Lakh+",
    official_documents: ["Degree Certificate","Marksheets","GRE/GMAT/IELTS scores","Admission Letter","LORs","Passport"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 75,
        display_text: "Minimum Marks 75 %",
        source_text: "Minimum Marks 75 %",
      }
    ],
  },
  {
    name: "Raman Kant Munjal Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Raman Kant Munjal Foundation",
    url: "https://www.indiascholarships.in/scholarships/raman-kant-munjal-scholarship",
    deadline: "2026-08-30",
    amount: "₹5.5 Lakh+",
    official_documents: ["Class 10 Marksheet","Class 12 Marksheet","Proof of current academic enrollment (College ID/fee receipt)","Parent's PAN card & masked Aadhaar card","Annual parental income proof (ITR/Income Certificate/salary slips)","Applicant's bank account details (passbook/cancelled cheque)","Bank account statements of parents","Affidavit declaring document authenticity","LinkedIn Profile URL"],
    criteria: [
      {
        field: "year_of_study",
        operator: "eq",
        value: 1,
        display_text: "Year of study equals 1 (first-year UG)",
        source_text: "The Raman Kant Munjal Scholarship 2026 offers up to ₹5.5 Lakhs per year to first-year finance and commerce undergraduate students with family incomes under ₹6 Lakh.",
      },
      {
        field: "branch",
        operator: "eq",
        value: "finance and commerce",
        display_text: "Branch equals finance and commerce",
        source_text: "The Raman Kant Munjal Scholarship 2026 offers up to ₹5.5 Lakhs per year to first-year finance and commerce undergraduate students with family incomes under ₹6 Lakh.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Annual family income less than or equal to 600000",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 80,
        display_text: "Percentage at least 80%",
        source_text: "Minimum Marks 80 %",
      }
    ],
  },
  {
    name: "Kotak Kanya Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "Kotak Education Foundation",
    url: "https://www.indiascholarships.in/scholarships/kotak-kanya-scholarship",
    deadline: "2026-08-30",
    amount: "₹1.5 Lakh+",
    official_documents: ["Class 10 & 12 marks memo showing >= 75%","Family Income Certificate (< ₹6 Lakhs)","College Fee receipts & admission letter","Student's Aadhaar card & passport photo","Aadhaar-seeded bank account details"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 75,
        display_text: "Minimum Marks 75 %",
        source_text: "Minimum Marks 75 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Income Limit Up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      }
    ],
  },
  {
    name: "L'Or'éal India For Young Women in Science (FYWIS) Scholarship 2026-27: Application Form, Eligibility & Selection List",
    provider: "L'Or'éal India",
    url: "https://www.indiascholarships.in/scholarships/loreal-fyws-scholarship",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    official_documents: ["Identity proof","Income certificate","Academic transcripts","Admission proof"],
    criteria: [
      {
        field: "percentage",
        operator: "gte",
        value: 85,
        display_text: "Class 12 Science PCM/B score >= 85%",
        source_text: "— Shortlisting based on academic merit (minimum 85% in Class 12 Science PCM/B for UG, minimum 60% in graduation for PG) and family income limit (<= ₹6,00,000 per annum)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "UG score >= 60%",
        source_text: "— Shortlisting based on academic merit (minimum 85% in Class 12 Science PCM/B for UG, minimum 60% in graduation for PG) and family income limit (<= ₹6,00,000 per annum)",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Household income <= 6,00,000 per annum",
        source_text: "— Shortlisting based on academic merit (minimum 85% in Class 12 Science PCM/B for UG, minimum 60% in graduation for PG) and family income limit (<= ₹6,00,000 per annum)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 85,
        display_text: "Minimum marks 85%",
        source_text: "Minimum Marks 85 %",
      }
    ],
  },
  {
    name: "Tata Realty Scholarship for Girls 2026-27: Application Form, Eligibility & Selection List",
    provider: "Tata Realty and Infrastructure Limited",
    url: "https://www.indiascholarships.in/scholarships/tata-realty-scholarship-for-girls",
    deadline: "2026-10-30",
    amount: "₹1.0 Lakh+",
    official_documents: ["Aadhaar Card","Class 10 and 12 Marksheets","Income Certificate (less than 5 Lakhs)","B.Arch Admission Proof","Current Year Fee Receipt","Bank Passbook copy"],
    criteria: [
      {
        field: "branch",
        operator: "eq",
        value: "B.Arch",
        display_text: "Branch: B.Arch",
        source_text: "Education Level UG (B.Arch)",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 60,
        display_text: "Minimum marks: 60%",
        source_text: "Minimum Marks 60 %",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 500000,
        display_text: "Annual family income limit: up to ₹5 Lakh per year",
        source_text: "Income Limit Up to ₹5.0 Lakh/year",
      },
      {
        field: "gender",
        operator: "eq",
        value: "female",
        display_text: "Gender: female",
        source_text: "Note: Exclusively for female students pursuing B.Arch degree.",
      }
    ],
  },
  {
    name: "AICTE Pragati Scholarship for Girl Students 2026-27",
    provider: "All India Council for Technical Education (AICTE), Government of India",
    url: "https://www.indiascholarships.in/scholarships/aicte-pragati-scholarship-for-girl-students",
    deadline: "2026-10-30",
    amount: "₹50k+",
    official_documents: ["Aadhaar card of the girl student","Family Income Certificate (< ₹8 Lakhs)","Class 10 & 12 marksheets","Admission receipt and AICTE approved college bonafide certificate","Aadhaar-seeded bank account details"],
    criteria: [
      {
        field: "gender",
        operator: "eq",
        value: "Female",
        display_text: "Female students",
        source_text: "Note: Restricted to AICTE-approved institutions and female students.",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 800000,
        display_text: "Annual family income must be at most ₹8 Lakhs per year",
        source_text: "Income Limit Up to ₹8.0 Lakh/year",
      },
      {
        field: "percentage",
        operator: "gte",
        value: 33,
        display_text: "Minimum marks percentage: at least 33%",
        source_text: "Minimum Marks 33 %",
      },
      {
        field: "institution_type",
        operator: "eq",
        value: "AICTE-approved",
        display_text: "Institution type must be AICTE-approved",
        source_text: "Note: Restricted to AICTE-approved institutions and female students.",
      }
    ],
  },
  {
    name: "Digital Gujarat Scholarship Portal (Pre-Matric & Post-Matric) 2026-27",
    provider: "Government of Gujarat",
    url: "https://www.indiascholarships.in/scholarships/digital-gujarat-scholarship-portal",
    deadline: "2026-09-29",
    amount: "₹60k+",
    official_documents: ["Aadhaar Card","Caste Certificate","Income Certificate (issued by Mamlatdar/TDO)","School/College Leaving Certificate","Hostel Certificate (if applicable)","Bank passbook page"],
    criteria: [
      {
        field: "state",
        operator: "eq",
        value: "Gujarat",
        display_text: "Domicile State Gujarat",
        source_text: "Domicile State Gujarat",
      },
      {
        field: "annual_family_income",
        operator: "lte",
        value: 600000,
        display_text: "Income Limit Up to ₹6.0 Lakh/year",
        source_text: "Income Limit Up to ₹6.0 Lakh/year",
      }
    ],
  }
];
