import type { MatchGroups, UserProfile } from "./types";

export const DEMO_USER: UserProfile = {
  name: "John Doe",
  cgpa: 8.5,
  year: 3,
  branch: "Computer Science & Engineering",
  state: "Karnataka",
  income: 250000,
  institutionType: "Government",
  category: "General",
  gender: "Male",
};

export const DEMO_GROUPS: MatchGroups = {
  eligible: [
    {
      scholarship: {
        id: "demo-1",
        title: "Foundation for Excellence (FFE) Scholarship 2026-27",
        provider: "Foundation for Excellence",
        amount: "₹1.0 Lakh+",
        deadline: "2026-10-30",
        url: "https://ffe.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c1", kind: "cgpa", operator: "gte", value: 7.0, label: "Minimum CGPA 7.0", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 7.0",
          reason: "Passes CGPA requirement",
          detail: "Your CGPA meets the minimum 7.0 requirement.",
          actual: "8.5",
          required: "7.0",
        },
        {
          criterion: { id: "c2", kind: "income", operator: "lte", value: 300000, label: "Family income ≤ ₹3.0L", short: "Income" },
          status: "pass",
          comparison: "Family income ₹2.5L ≤ ₹3.0L",
          reason: "Passes income threshold",
          detail: "Your income is within the ₹3.0L limit.",
          actual: "₹2.5L",
          required: "₹3.0L",
        },
        {
          criterion: { id: "c3", kind: "branch", operator: "in", value: ["CS", "IT", "ECE"], label: "Engineering Streams", short: "Branch" },
          status: "pass",
          comparison: "Branch Engineering = Valid",
          reason: "Passes branch requirement",
          detail: "Your branch is eligible.",
          actual: "CS",
          required: "CS/IT/ECE",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-2",
        title: "SBI Asha Scholarship 2026-27: UG Engineering Grant",
        provider: "SBI Foundation",
        amount: "₹50,000",
        deadline: "2026-11-15",
        url: "https://sbifoundation.in",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c4", kind: "cgpa", operator: "gte", value: 7.5, label: "Minimum CGPA 7.5", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 7.5",
          reason: "Passes CGPA requirement",
          detail: "Your CGPA meets requirement.",
          actual: "8.5",
          required: "7.5",
        },
        {
          criterion: { id: "c5", kind: "income", operator: "lte", value: 600000, label: "Family income ≤ ₹6.0L", short: "Income" },
          status: "pass",
          comparison: "Family income ₹2.5L ≤ ₹6.0L",
          reason: "Passes income threshold",
          detail: "Income within threshold.",
          actual: "₹2.5L",
          required: "₹6.0L",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-3",
        title: "CM Raitha Vidya Nidhi - Farmer's Children Scholarship",
        provider: "Government of Karnataka",
        amount: "₹11,000",
        deadline: "2026-12-31",
        url: "https://ssp.karnataka.gov.in",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c6", kind: "state", operator: "eq", value: "Karnataka", label: "Karnataka Resident", short: "State" },
          status: "pass",
          comparison: "Domicile Karnataka = Eligible",
          reason: "Karnataka Resident",
          detail: "Karnataka domicile verified.",
          actual: "Karnataka",
          required: "Karnataka",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-4",
        title: "National Merit Cum Means Scholarship (NMMSS) 2026",
        provider: "Ministry of Education",
        amount: "₹12,000/yr",
        deadline: "2026-10-15",
        url: "https://scholarships.gov.in",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c7", kind: "cgpa", operator: "gte", value: 6.0, label: "Minimum CGPA 6.0", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 6.0",
          reason: "Passes CGPA check",
          detail: "Above required CGPA.",
          actual: "8.5",
          required: "6.0",
        },
        {
          criterion: { id: "c8", kind: "income", operator: "lte", value: 350000, label: "Income ≤ ₹3.5L", short: "Income" },
          status: "pass",
          comparison: "Family income ₹2.5L ≤ ₹3.5L",
          reason: "Passes income requirement",
          detail: "Within limits.",
          actual: "₹2.5L",
          required: "₹3.5L",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-5",
        title: "Kotak Kanya Scholarship 2026-27 for STEM Students",
        provider: "Kotak Education Foundation",
        amount: "₹1.5 Lakh",
        deadline: "2026-09-30",
        url: "https://kotakeducation.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c9", kind: "cgpa", operator: "gte", value: 8.0, label: "Minimum CGPA 8.0", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 8.0",
          reason: "Passes academic requirement",
          detail: "Meets score.",
          actual: "8.5",
          required: "8.0",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-6",
        title: "Reliance Foundation Undergraduate Scholarship 2026",
        provider: "Reliance Foundation",
        amount: "₹2.0 Lakh",
        deadline: "2026-10-06",
        url: "https://scholarships.reliancefoundation.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c10", kind: "cgpa", operator: "gte", value: 7.5, label: "Minimum CGPA 7.5", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 7.5",
          reason: "Passes requirement",
          detail: "Passes CGPA check.",
          actual: "8.5",
          required: "7.5",
        },
        {
          criterion: { id: "c11", kind: "income", operator: "lte", value: 1500000, label: "Income ≤ ₹15.0L", short: "Income" },
          status: "pass",
          comparison: "Family income ₹2.5L ≤ ₹15.0L",
          reason: "Income check passed",
          detail: "Passes income.",
          actual: "₹2.5L",
          required: "₹15.0L",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-7",
        title: "SSP Post-Matric Scholarship (Karnataka) 2026-27",
        provider: "Social Welfare Dept, Karnataka",
        amount: "Tuition + Hostel",
        deadline: "2026-11-30",
        url: "https://ssp.postmatric.karnataka.gov.in",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c12", kind: "state", operator: "eq", value: "Karnataka", label: "Karnataka Domicile", short: "State" },
          status: "pass",
          comparison: "State Karnataka = Resident",
          reason: "Passes state requirement",
          detail: "Karnataka resident verified.",
          actual: "Karnataka",
          required: "Karnataka",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-8",
        title: "TATA Building India Scholarship 2026",
        provider: "Tata Trust",
        amount: "₹60,000",
        deadline: "2026-12-15",
        url: "https://tatatrusts.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c13", kind: "cgpa", operator: "gte", value: 8.0, label: "Minimum CGPA 8.0", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 8.0",
          reason: "Passes academic requirement",
          detail: "Eligible.",
          actual: "8.5",
          required: "8.0",
        },
      ],
      failures: [],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-9",
        title: "HDFC Bank Parivartan's ECSS Scholarship 2026-27",
        provider: "HDFC Bank",
        amount: "₹75,000",
        deadline: "2026-10-31",
        url: "https://hdfcbank.com",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "ELIGIBLE",
      results: [
        {
          criterion: { id: "c14", kind: "cgpa", operator: "gte", value: 6.0, label: "Minimum CGPA 6.0", short: "CGPA" },
          status: "pass",
          comparison: "CGPA 8.5 ≥ 6.0",
          reason: "Passes academic requirement",
          detail: "Eligible.",
          actual: "8.5",
          required: "6.0",
        },
      ],
      failures: [],
      nearMisses: [],
    },
  ],
  nearMiss: [
    {
      scholarship: {
        id: "demo-nm1",
        title: "XYZ Foundation Merit Grant 2026",
        provider: "XYZ Foundation",
        amount: "₹1.2 Lakh",
        deadline: "2026-09-20",
        url: "https://xyzfoundation.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "NEAR_MISS",
      results: [],
      failures: [],
      nearMisses: [
        {
          criterion: { id: "nm1", kind: "cgpa", operator: "gte", value: 8.8, label: "Minimum CGPA 8.8", short: "CGPA" },
          status: "near",
          comparison: "CGPA 8.5 < 8.8",
          reason: "0.3 CGPA short",
          detail: "Your CGPA of 8.5 is 0.3 points below the 8.8 cutoff.",
          actual: "8.5",
          required: "8.8",
        },
      ],
    },
    {
      scholarship: {
        id: "demo-nm2",
        title: "Aditya Birla Capital Scholarship for Post-Graduates",
        provider: "Aditya Birla Capital Foundation",
        amount: "₹60,000",
        deadline: "2026-10-15",
        url: "https://adityabirlacapital.com",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "NEAR_MISS",
      results: [],
      failures: [],
      nearMisses: [
        {
          criterion: { id: "nm2", kind: "year_of_study", operator: "gte", value: 4, label: "Final Year Students Only", short: "Year" },
          status: "near",
          comparison: "Year 3 < Year 4",
          reason: "1 year short",
          detail: "This opportunity requires Year 4 students.",
          actual: "3",
          required: "4",
        },
      ],
    },
    {
      scholarship: {
        id: "demo-nm3",
        title: "Sitaram Jindal Foundation Scholarship Scheme",
        provider: "Sitaram Jindal Foundation",
        amount: "₹25,000",
        deadline: "2026-11-10",
        url: "https://sitaramjindalfoundation.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "NEAR_MISS",
      results: [],
      failures: [],
      nearMisses: [
        {
          criterion: { id: "nm3", kind: "income", operator: "lte", value: 200000, label: "Family income ≤ ₹2.0L", short: "Income" },
          status: "near",
          comparison: "Family income ₹2.5L > ₹2.0L",
          reason: "₹50,000 over income cap",
          detail: "Your family income exceeds the ₹2.0L ceiling.",
          actual: "₹2.5L",
          required: "₹2.0L",
        },
      ],
    },
  ],
  notEligible: [
    {
      scholarship: {
        id: "demo-rej1",
        title: "ABC Super 30 Special Science Scholarship",
        provider: "ABC Educational Trust",
        amount: "₹80,000",
        deadline: "2026-08-30",
        url: "https://abctrust.org",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "NOT_ELIGIBLE",
      results: [
        {
          criterion: { id: "rej1", kind: "income", operator: "lte", value: 150000, label: "Income ≤ ₹1.5L", short: "Income" },
          status: "fail",
          comparison: "Family income ₹2.5L exceeds maximum ₹1.5L",
          reason: "Family income exceeds ₹1.5L",
          detail: "Your family income of ₹2.5L exceeds the maximum allowed income of ₹1.5L.",
          actual: "₹2.5L",
          required: "₹1.5L",
        },
      ],
      failures: [
        {
          criterion: { id: "rej1", kind: "income", operator: "lte", value: 150000, label: "Income ≤ ₹1.5L", short: "Income" },
          status: "fail",
          comparison: "Family income ₹2.5L exceeds maximum ₹1.5L",
          reason: "Family income exceeds ₹1.5L",
          detail: "Your family income of ₹2.5L exceeds the maximum allowed income of ₹1.5L.",
          actual: "₹2.5L",
          required: "₹1.5L",
        },
      ],
      nearMisses: [],
    },
    {
      scholarship: {
        id: "demo-rej2",
        title: "Post-Graduate Research Fellowship 2026",
        provider: "CSIR-HRDG",
        amount: "₹31,000/pm",
        deadline: "2026-09-15",
        url: "https://csirhrdg.res.in",
        category: "scholarship",
        locationType: "india",
        officialRequirements: [],
        communityRequirements: [],
        criteria: [],
      },
      status: "NOT_ELIGIBLE",
      results: [
        {
          criterion: { id: "rej2", kind: "degree", operator: "eq", value: "Masters", label: "Post-Graduate Degree Only", short: "Degree" },
          status: "fail",
          comparison: "Degree UnderGraduate ≠ PostGraduate",
          reason: "Requires Master's degree",
          detail: "Only PG/Master's students qualify.",
          actual: "UG",
          required: "PG",
        },
      ],
      failures: [
        {
          criterion: { id: "rej2", kind: "degree", operator: "eq", value: "Masters", label: "Post-Graduate Degree Only", short: "Degree" },
          status: "fail",
          comparison: "Degree UnderGraduate ≠ PostGraduate",
          reason: "Requires Master's degree",
          detail: "Only PG/Master's students qualify.",
          actual: "UG",
          required: "PG",
        },
      ],
      nearMisses: [],
    },
  ],
};

export const DEMO_NOTIFICATIONS = [
  {
    id: "notif-1",
    userId: "demo-user-id",
    type: "matching_opportunity" as const,
    title: "AI Innovation Hackathon 2026",
    message: "New hackathon matches your profile (Computer Science & Engineering).",
    link: "/opportunities",
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "notif-2",
    userId: "demo-user-id",
    type: "deadline_approaching" as const,
    title: "FFE Scholarship Deadline Approaching",
    message: "Foundation for Excellence application closes in 5 days.",
    link: "/apply/demo-1",
    isRead: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "notif-3",
    userId: "demo-user-id",
    type: "status_changed" as const,
    title: "Submitted Opportunity Pending Review",
    message: "Your submission 'National Student Tech Summit' is currently pending review.",
    link: "/opportunities/my",
    isRead: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const DEMO_PLATFORM_OPPORTUNITIES = [
  {
    id: "opp-h1",
    name: "AI Innovation Hackathon 2026",
    provider: "ABC Technologies & Dev Community",
    organization: "ABC Technologies",
    url: null,
    deadline: "2026-09-18",
    amount: "₹2.5 Lakh Prize Pool",
    category: "hackathon" as const,
    locationType: "india" as const,
    funded: true,
    description: "Build real-world AI and software solutions with a student team over 48 hours. Open to engineering & science undergraduates.",
    tags: ["AI", "Software", "Innovation"],
    skills: ["Python", "React", "Machine Learning"],
    status: "published" as const,
    applicationMode: "eligent" as const,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "opp-i1",
    name: "Frontend Engineering Summer Internship 2026",
    provider: "Nexus Software Labs",
    organization: "Nexus Software Labs",
    url: null,
    deadline: "2026-10-10",
    amount: "₹35,000 / month",
    category: "internship" as const,
    locationType: "online" as const,
    funded: true,
    description: "Remote 3-month engineering internship working with React, Next.js, and modern Web APIs. Mentorship provided.",
    tags: ["Frontend", "React", "Remote"],
    skills: ["TypeScript", "React", "CSS"],
    status: "published" as const,
    applicationMode: "eligent" as const,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "opp-e1",
    name: "National Student Developers Summit 2026",
    provider: "Developer Student Clubs India",
    organization: "DSC India",
    url: "https://dscindia.org/summit-2026",
    deadline: "2026-11-05",
    amount: "Free Registration",
    category: "event" as const,
    locationType: "india" as const,
    funded: false,
    description: "A 2-day hands-on summit featuring tech talks, networking with industry leaders, and live product demos.",
    tags: ["Conference", "Networking", "DevOps"],
    skills: ["Cloud", "Web Development"],
    status: "published" as const,
    applicationMode: "external" as const,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "opp-w1",
    name: "Cloud Native & Kubernetes Hands-on Workshop",
    provider: "Open Source India Community",
    organization: "OSI",
    url: "https://opensourceindia.in/workshops/cloud-native",
    deadline: "2026-09-25",
    amount: "Free",
    category: "workshop" as const,
    locationType: "online" as const,
    funded: false,
    description: "Learn containerization, Docker, and Kubernetes deployment fundamentals from certified cloud architects.",
    tags: ["Kubernetes", "Docker", "Cloud"],
    skills: ["Linux", "Docker"],
    status: "published" as const,
    applicationMode: "external" as const,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "opp-f1",
    name: "Young Tech Leaders Fellowship 2026-27",
    provider: "Global Leadership Institute",
    organization: "GLI Foundation",
    url: null,
    deadline: "2026-12-01",
    amount: "₹5.0 Lakh Fellowship Grant",
    category: "fellowship" as const,
    locationType: "abroad" as const,
    funded: true,
    description: "Fully funded 6-month leadership and research fellowship for high-achieving undergraduate students.",
    tags: ["Fellowship", "Global", "Research"],
    skills: ["Leadership", "Research"],
    status: "published" as const,
    applicationMode: "eligent" as const,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
];

